version: "3.8"

services:
  bot:
    build:
      context: . # Используется Dockerfile из текущей директории
    ports:
      - "8080:8080" # Порт, на котором бот слушает запросы
    environment:
      - "BOT_TOKEN=7923080732:AAFD4H1EGL4N6if7QJJDaqXiA6GeVSAT0nY"
      - "DB_HOST=my-db-host.onrender.com"
      - "DB_PORT=5432" # Внутренний порт базы данных
      - "DB_USER=root"
      - "DB_PASSWORD=secret"
      - "DB_NAME=postgres"
      - "USER_CHECK_ID=710606281"
      - "PAY_URL=https://www.instagram.com/kaspi.kz/?hl=en"
    depends_on:
      - db

  db:
    image: postgres:16-alpine # Легкий образ PostgreSQL
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5433:5432" # Внешний порт 5433 мапится на внутренний 5432
