version: "3.8"

services:
  bot:
    build:
      context: . # Используется Dockerfile из текущей директории
    ports:
      - "8080:8080" # Порт, на котором бот слушает запросы
    environment:
      - BOT_TOKEN=7923080732:AAFD4H1EGL4N6if7QJJDaqXiA6GeVSAT0nY
      - USER_CHECK_ID=710606281
      - PAY_URL=https://www.instagram.com/kaspi.kz/?hl=en
      - DB_HOST=dpg-ctqk213tq21c73a2te1g-a.oregon-postgres.render.com
      - DB_PORT=5432
      - DB_NAME=checkdatabase
      - DB_USER=root
      - DB_PASSWORD=4lnv041DhUf1BYeFmnX09lRPEVN2SaFV
      - DB_SSLMODE=require
    depends_on:
      - db

  db:
    image: postgres:16-alpine # Легкий образ PostgreSQL
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4lnv041DhUf1BYeFmnX09lRPEVN2SaFV
      POSTGRES_DB: checkdatabase
    ports:
      - "10000:10000"