// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type User struct {
	ID            int32        `json:"id"`
	UserID        string       `json:"user_id"`
	Username      string       `json:"username"`
	Purchased     sql.NullBool `json:"purchased"`
	LanguageCode  string       `json:"language_code"`
	ChosenPackage string       `json:"chosen_package"`
}
